import { Types } from "mongoose";
import cloudinary from "../config/cloudinary";
import { Subscription } from "../models/subscription.model";
import { VideoVisibility } from "../models/video.model";
import { ApiError } from "../utils/apiError";
import crypto from "crypto";
import { generateThumbnails } from "../utils/generateThumbnails";
import { getCached, invalidateCache, setCached } from "./redis.service";
import { videoRepository } from "../repositories/video.repository";

interface ChannelProfile {
  _id: string;
  name: string;
  avatar: string;
  subscriberCount: number;
}

interface UploadVideoPayload {
  videoFile: {
    url: string;
    publicId: string;
  };
  duration: number;
  thumbnail: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  visibility: VideoVisibility;
}
interface VideoResult {
  video: {
    id: string;
    title: string;
    description: string;
    thumbnail: string;
    duration: number;
    tags: Array<string>;
    createdAt: Date;
    stats: {
      views: number;
      likesCount: number;
      commentsCount: number;
    };
    channel: ChannelProfile;
  };
  isSubscribed: boolean;
}

// Metadata Payload
interface MetadataPayload {
  title: string;
  description: string;
  category: string;
  tags: string[];
  playlist: string;
  visibility: string;
}

// Get home feed videos service
export const getFeedService = async (page: number, limit: number) => {
  // Calculate offset pagination
  const skip = (page - 1) * limit;

  // fetch all the videos available on the platform
  const [videos, totalVideos] = await videoRepository.findFeed(skip, limit);

  // Calculate Total Pages for pagination
  const totalPages = Math.ceil(totalVideos / limit);
  // return the videos including pagination
  return {
    videos,
    pagination: {
      page,
      limit,
      totalVideos,
      totalPages,
      hasNextPage: page < totalPages,
    },
  };
};

// Get single video service
export const getSingleVideoService = async (
  // get the id's
  videoId: string,
  viewerId?: string
): Promise<VideoResult> => {
  // get the video from cache first
  let videoData: VideoResult["video"] | null = await getCached(
    `video-details:${videoId}`
  );

  if (!videoData) {
    // find the video which is ready and visible and populate channel with it
    const video = await videoRepository.findVideoWithChannelInfo(videoId);
    // check if the video exists or not
    if (!video) {
      throw new ApiError(404, "Video Not Found!");
    }

    videoData = {
      id: video._id.toString(),
      title: video.title,
      description: video.description,
      thumbnail: video.thumbnail?.url ?? "",
      duration: video.duration,
      tags: video.tags,
      createdAt: video.createdAt,
      stats: {
        views: video.views,
        likesCount: video.likesCount,
        commentsCount: video.commentsCount,
      },
      channel: {
        _id: video.channel._id.toString(),
        name: video.channel.name,
        avatar: video.channel.avatar,
        subscriberCount: video.channel.subscriberCount,
      },
    };

    // set the new data to the cache
    await setCached(`video-details:${videoId}`, videoData, 300);
  }

  // check if the viewer subscribed to this channel or not
  let isSubscribed = false;

  if (viewerId) {
    const subscriptionExists = !!(await Subscription.exists({
      channel: videoData.channel._id,
      subscriber: viewerId,
    }));

    isSubscribed = subscriptionExists;
  }

  return {
    video: videoData,
    isSubscribed,
  };
};

// Uploading Video
// Get upload signature service
export const getUploadSignatureService = async () => {
  // This signature is generated by Cloudinary SDK
  const timestamp = Math.round(Date.now() / 1000);

  const paramsToSign = {
    timestamp,
    folder: Bun.env.CLOUDINARY_FOLDER,
    resource_type: "videos",
  };

  const signature = cloudinary.utils.api_sign_request(
    paramsToSign,
    Bun.env.CLOUDINARY_API_SECRET as string
  );

  return {
    timestamp,
    signature,
    apiKey: Bun.env.CLOUDINARY_API_KEY,
    cloudName: Bun.env.CLOUDINARY_CLOUD_NAME,
    folder: Bun.env.CLOUDINARY_FOLDER,
  };
};

// create Video record / upload video
export const uploadVideoService = async (
  channelId: string,
  payload: UploadVideoPayload
) => {
  // check if the payload are valid or not
  if (!payload.videoFile.url || !payload.videoFile.publicId) {
    throw new ApiError(400, "Invalid Video File Payload");
  }
  // check all the required fields
  if (!payload.duration || payload.duration === 0) {
    throw new ApiError(400, "Invalid duration");
  }

  if (!payload.title || payload.title.trim() === "") {
    throw new ApiError(400, "Title is required");
  }

  // check if the thumbnail is valid or not
  const validThumbnail = generateThumbnails(
    payload.videoFile.publicId,
    payload.duration
  );

  if (!payload.thumbnail || !validThumbnail.includes(payload.thumbnail)) {
    throw new ApiError(400, "Invalid thumbnail");
  }
  // create the video record in DB but keep the metadata empty
  const createVideoRecord = await videoRepository.createVideo({
    channel: channelId,
    videoFile: {
      url: payload.videoFile.url,
      publicId: payload.videoFile.publicId,
    },
    duration: payload.duration,
    title: payload.title,
    description: payload.description || "",
    category: payload.category,
    tags: payload.tags || [],
    visibility: payload.visibility || VideoVisibility.PRIVATE,
    views: 0,
    likesCount: 0,
    commentsCount: 0,
  });
  // return the video
  return createVideoRecord;
};

// Update Metadata Service
export const updateMetadataService = async (
  // get the video and channel Id
  videoId: string,
  channelId: string,
  { title, description, category, tags, playlist, visibility }: MetadataPayload
) => {
  // find the video
  const video = await videoRepository.findVideoByChannel(videoId, channelId);
  // check if video exists or
  if (!video) {
    throw new ApiError(404, "Video Not Found!");
  }
  // update the video metadata and save the video
  await videoRepository.updateVideoMetadata(video, {
    title,
    description,
    category,
    tags,
    playlist: new Types.ObjectId(playlist),
    visibility: visibility as VideoVisibility,
  });

  // after updating metadata, invalidate Single video
  await invalidateCache(`video-details:${videoId}`);

  // return the updated video
  return video;
};

// Engagement Services
// Adding view Service
export const addViewService = async (
  videoId: string,
  userId: string | null,
  sessionId: string
) => {
  // check who is the user - is the user logged in or not
  let viewerKey: string = "";

  let newSessionId = null; // session is assigned to logged out user, so that they can watch the video easily it will be check if the browser contains that session id or not, if not then we create one and if it exists then use that
  if (userId) {
    viewerKey = `user-${userId}`;
  } else {
    if (!sessionId) {
      sessionId = crypto.randomUUID();
      // set session cookie for 30 days
      newSessionId = sessionId;
    }
    viewerKey = sessionId;
  }
  // check if the viewer already watched the video or not
  const existingView = await videoRepository.findExistingView(
    viewerKey,
    videoId
  );

  const now = new Date();

  if (!existingView) {
    await videoRepository.createView(videoId, viewerKey, now);
    // after creating view document increment the view count in video
    await videoRepository.incrementView(videoId);

    return { counted: true, newSessionId };
  }

  const VIEW_WINDOW = 1000 * 60 * 60 * 3; // set view window of 3 hrs

  const timeDiff = now.getTime() - existingView.lastCountedAt.getTime(); // this calculates the time difference - if the user watched the video at 12 P.M. and right now it's 4 P.M. then the difference is 4 hrs, it will store the difference

  // After that we check if the time difference is greater than 3 hrs count the view on the same video otherwise it won't count the view

  if (timeDiff > VIEW_WINDOW) {
    await videoRepository.updateViewTimestamp(existingView, now);
    await videoRepository.incrementView(videoId);
    return { counted: true, newSessionId };
  }

  return { counted: false, newSessionId };
};

// Liking or un-liking video
export const toggleLikeService = async (userId: string, videoId: string) => {
  // check if the like already exists or not
  const existingLike = await videoRepository.findLike(userId, videoId);
  // if the video is liked already than delete the like
  if (existingLike) {
    await videoRepository.deleteLike(existingLike._id.toString());

    // and update the video likes count
    const unlikeVideo = await videoRepository.adjustLikeCount(videoId, -1);

    // return the like status and like count
    return {
      liked: false,
      likesCount: unlikeVideo?.likesCount,
    };
  }
  // if video is not liked then add the like
  await videoRepository.createLike(userId, videoId);
  // Then update the like count in video
  const likeVideo = await videoRepository.adjustLikeCount(videoId, 1);
  // return the like status and like count
  return { liked: true, likesCount: likeVideo?.likesCount };
};

// Get Comments of video
export const getCommentsService = async (
  videoId: string,
  page: number,
  limit: number
) => {
  // calculate offset pagination
  const skip = (page - 1) * limit;
  // find all the comments with pagination
  const [comments, totalComments] = await videoRepository.findVideoComments(
    videoId,
    skip,
    limit
  );

  // Calculate total pages
  const totalPages = Math.ceil(totalComments / limit);
  // return the paginated result
  return {
    comments,
    pagination: {
      page,
      limit,
      totalComments,
      currentPage: page,
      totalPages,
      hasNextPage: page < totalPages,
    },
  };
};

// Post Comment
export const postCommentService = async (
  // get the id's and content
  userId: string,
  videoId: string,
  content: string
) => {
  // get the video
  const video = await videoRepository.findVideoById(videoId);

  // check if the video exists or not
  if (!video) {
    throw new ApiError(404, "Video not Found");
  }

  // if video exists then create a comment
  const postComment = await videoRepository.createComment(
    videoId,
    userId,
    content
  );
  // update the comment count in video
  await videoRepository.incrementCommentCount(videoId);

  // after adding comment, invalidate single video cache
  await invalidateCache(`video-details:${videoId}`);

  // return the updated response
  return postComment;
};

// Update Comment Service
export const updateCommentService = async (
  // get the id's and content
  userId: string,
  commentId: string,
  content: string
) => {
  // find the comment
  const comment = await videoRepository.findCommentById(commentId);
  // check if the comment exists or not
  if (!comment) {
    throw new ApiError(404, " Comment Not Found");
  }
  // check if the comment owner is same
  if (comment.user.toString() !== userId) {
    throw new ApiError(400, "You are unauthorized to edit");
  }
  // update the comment content and save to DB
  await videoRepository.updateComment(comment, content);
  // return the updated comment
  return comment;
};

// Delete Comment Service
export const deleteCommentService = async (
  // get hte id's
  userId: string,
  commentId: string
) => {
  // find the comment and delete
  const comment = await videoRepository.deleteComment(commentId, userId);
  // check if the comment exists or not
  if (!comment) {
    throw new ApiError(404, "Comment Not found or Unauthorized");
  }
  // update the comment count in video and also set the comment counter minimum go to zero
  await videoRepository.decrementCommentCount(comment.video);

  // after deleting the comment, invalidate single video cache
  await invalidateCache(`video-details:${comment.video.toString()}`);

  // return the response
  return true;
};

// Get Related Videos
export const getRelatedVideosService = async (videoId: string) => {
  // get the videoId
  // find the video and select the tags and category
  const video = await videoRepository.findByTagsAndCategory(videoId);
  // check if the video exists or not
  if (!video) {
    throw new ApiError(404, "Video Not Found");
  }
  // find the related video using tags or category but do not include this video
  const relatedVideos = await videoRepository.findRelatedVideos(
    videoId,
    video.tags,
    video.category
  );
  // return the related videos
  return relatedVideos;
};
