name: Deploy Orbit Studio

on:
  push:
    branches:
      - main

concurrency:
  group: orbit-studio-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Orbit Studio to EC2
        run: |
          set -e

          echo "Starting Deployment..."

          cd /home/ubuntu/Orbit_Studio
          git pull origin main
          /home/ubuntu/.bun/bin/bun install
          /home/ubuntu/.bun/bin/bun run build
          /home/ubuntu/.bun/bin/pm2 restart orbit-studio
